language: java
jdk:
  - oraclejdk8
install: true
dist: trusty
os: linux

jobs:
  include:
    - stage: build
      script: mvn clean test
    - stage: deploy
      script: mvn deploy

stages:
  - name: build
  - name: deploy
    if: branch =~ ^release.*$
