language: java
jdk:
- oraclejdk8
install: true
dist: trusty
os: linux
before_install:
  - openssl aes-256-cbc -K $encrypted_404964577bd1_key -iv $encrypted_404964577bd1_iv -in all.gpg.enc -out all.gpg -d

jobs:
  include:
    - stage: build
      script: mvn clean test
    - stage: deploy
      script: mvn deploy
stages:
  - name: build
    if: branch !~ ^release.*$
  - name: deploy
    if: branch =~ ^release.*$
