language: java
jdk:
  - oraclejdk8
install: true
dist: trusty
os: linux
env:
  - RELEASE=false

before_install:
  - openssl aes-256-cbc -K $encrypted_404964577bd1_key -iv $encrypted_404964577bd1_iv -in all.gpg.enc -out all.gpg -d
  - gpg --import all.gpg
  - cp settings.xml $HOME/.m2/settings.xml

jobs:
  include:
    - stage: build
      script: mvn -U clean install
    - stage: startRelease
      script: mvn -U clean jgitflow:release-start -PgitflowStart
    - stage: finishRelease
      script: mvn -U clean jgitflow:release-finish -PgitflowFinish
stages:
  - name: build
    if: branch !~ ^release.*$
  - name: startRelease
    if: branch = develop AND env(RELEASE) = true
  - name: finishRelease
    if: branch =~ ^release.*$
