package com.github.squirrelgrip.scientist4k.http.core.model

import com.github.squirrelgrip.scientist4k.http.core.extension.isTextLike
import com.google.common.net.MediaType
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ExperimentResponseKtTest {

    @Test
    fun isTextLike() {
        assertIsNotTextLike(MediaType.AAC_AUDIO)
        assertIsNotTextLike(MediaType.ANY_APPLICATION_TYPE)
        assertIsNotTextLike(MediaType.ANY_AUDIO_TYPE)
        assertIsNotTextLike(MediaType.ANY_IMAGE_TYPE)
        assertIsTextLike(MediaType.ANY_TEXT_TYPE)
        assertIsNotTextLike(MediaType.ANY_TYPE)
        assertIsNotTextLike(MediaType.ANY_VIDEO_TYPE)
        assertIsNotTextLike(MediaType.APPLE_MOBILE_CONFIG)
        assertIsNotTextLike(MediaType.APPLE_PASSBOOK)
        assertIsNotTextLike(MediaType.APPLICATION_BINARY)
        assertIsTextLike(MediaType.APPLICATION_XML_UTF_8)
        assertIsTextLike(MediaType.ATOM_UTF_8)
        assertIsNotTextLike(MediaType.BASIC_AUDIO)
        assertIsNotTextLike(MediaType.BMP)
        assertIsNotTextLike(MediaType.BZIP2)
        assertIsTextLike(MediaType.CACHE_MANIFEST_UTF_8)
        assertIsNotTextLike(MediaType.CRW)
        assertIsTextLike(MediaType.CSS_UTF_8)
        assertIsTextLike(MediaType.CSV_UTF_8)
        assertIsTextLike(MediaType.DART_UTF_8)
        assertIsNotTextLike(MediaType.EOT)
        assertIsNotTextLike(MediaType.EPUB)
        assertIsNotTextLike(MediaType.FLV_VIDEO)
        assertIsTextLike(MediaType.FORM_DATA)
        assertIsTextLike(MediaType.GEO_JSON)
        assertIsNotTextLike(MediaType.GIF)
        assertIsNotTextLike(MediaType.GZIP)
        assertIsTextLike(MediaType.HAL_JSON)
        assertIsNotTextLike(MediaType.HEIF)
        assertIsTextLike(MediaType.HTML_UTF_8)
        assertIsTextLike(MediaType.I_CALENDAR_UTF_8)
        assertIsNotTextLike(MediaType.ICO)
        assertIsTextLike(MediaType.JAVASCRIPT_UTF_8)
        assertIsNotTextLike(MediaType.JOSE)
        assertIsNotTextLike(MediaType.JOSE_JSON)
        assertIsNotTextLike(MediaType.JP2K)
        assertIsNotTextLike(MediaType.JPEG)
        assertIsTextLike(MediaType.JSON_UTF_8)
        assertIsNotTextLike(MediaType.KEY_ARCHIVE)
        assertIsNotTextLike(MediaType.KML)
        assertIsNotTextLike(MediaType.KMZ)
        assertIsNotTextLike(MediaType.L16_AUDIO)
        assertIsNotTextLike(MediaType.L24_AUDIO)
        assertIsTextLike(MediaType.MANIFEST_JSON_UTF_8)
        assertIsNotTextLike(MediaType.MBOX)
        assertIsNotTextLike(MediaType.MEDIA_PRESENTATION_DESCRIPTION)
        assertIsNotTextLike(MediaType.MICROSOFT_EXCEL)
        assertIsNotTextLike(MediaType.MICROSOFT_OUTLOOK)
        assertIsNotTextLike(MediaType.MICROSOFT_POWERPOINT)
        assertIsNotTextLike(MediaType.MICROSOFT_WORD)
        assertIsNotTextLike(MediaType.MP4_AUDIO)
        assertIsNotTextLike(MediaType.MP4_VIDEO)
        assertIsNotTextLike(MediaType.MPEG_AUDIO)
        assertIsNotTextLike(MediaType.MPEG_VIDEO)
        assertIsNotTextLike(MediaType.NACL_APPLICATION)
        assertIsNotTextLike(MediaType.NACL_PORTABLE_APPLICATION)
        assertIsNotTextLike(MediaType.OCTET_STREAM)
        assertIsNotTextLike(MediaType.OGG_AUDIO)
        assertIsNotTextLike(MediaType.OGG_CONTAINER)
        assertIsNotTextLike(MediaType.OGG_VIDEO)
        assertIsNotTextLike(MediaType.OOXML_DOCUMENT)
        assertIsNotTextLike(MediaType.OOXML_PRESENTATION)
        assertIsNotTextLike(MediaType.OOXML_SHEET)
        assertIsNotTextLike(MediaType.OPENDOCUMENT_GRAPHICS)
        assertIsNotTextLike(MediaType.OPENDOCUMENT_PRESENTATION)
        assertIsNotTextLike(MediaType.OPENDOCUMENT_SPREADSHEET)
        assertIsNotTextLike(MediaType.OPENDOCUMENT_TEXT)
        assertIsTextLike(MediaType.OPENSEARCH_DESCRIPTION_UTF_8)
        assertIsNotTextLike(MediaType.PDF)
        assertIsTextLike(MediaType.PLAIN_TEXT_UTF_8)
        assertIsNotTextLike(MediaType.PNG)
        assertIsNotTextLike(MediaType.POSTSCRIPT)
        assertIsNotTextLike(MediaType.PROTOBUF)
        assertIsNotTextLike(MediaType.PSD)
        assertIsNotTextLike(MediaType.QUICKTIME)
        assertIsTextLike(MediaType.RDF_XML_UTF_8)
        assertIsTextLike(MediaType.RTF_UTF_8)
        assertIsNotTextLike(MediaType.SFNT)
        assertIsNotTextLike(MediaType.SHOCKWAVE_FLASH)
        assertIsNotTextLike(MediaType.SKETCHUP)
        assertIsTextLike(MediaType.SOAP_XML_UTF_8)
        assertIsTextLike(MediaType.SVG_UTF_8)
        assertIsNotTextLike(MediaType.TAR)
        assertIsTextLike(MediaType.TEXT_JAVASCRIPT_UTF_8)
        assertIsNotTextLike(MediaType.THREE_GPP2_VIDEO)
        assertIsNotTextLike(MediaType.THREE_GPP_VIDEO)
        assertIsNotTextLike(MediaType.TIFF)
        assertIsTextLike(MediaType.TSV_UTF_8)
        assertIsTextLike(MediaType.VCARD_UTF_8)
        assertIsNotTextLike(MediaType.VND_REAL_AUDIO)
        assertIsNotTextLike(MediaType.VND_WAVE_AUDIO)
        assertIsNotTextLike(MediaType.VORBIS_AUDIO)
        assertIsTextLike(MediaType.VTT_UTF_8)
        assertIsNotTextLike(MediaType.WASM_APPLICATION)
        assertIsNotTextLike(MediaType.WAX_AUDIO)
        assertIsNotTextLike(MediaType.WEBM_AUDIO)
        assertIsNotTextLike(MediaType.WEBM_VIDEO)
        assertIsNotTextLike(MediaType.WEBP)
        assertIsNotTextLike(MediaType.WMA_AUDIO)
        assertIsTextLike(MediaType.WML_UTF_8)
        assertIsNotTextLike(MediaType.WMV)
        assertIsNotTextLike(MediaType.WOFF)
        assertIsNotTextLike(MediaType.WOFF2)
        assertIsTextLike(MediaType.XHTML_UTF_8)
        assertIsTextLike(MediaType.XML_UTF_8)
        assertIsTextLike(MediaType.XRD_UTF_8)
        assertIsNotTextLike(MediaType.ZIP)
    }

    fun assertIsTextLike(mediaType: MediaType) {
        assertThat(mediaType.isTextLike()).describedAs(mediaType.toString()).isTrue()
    }

    fun assertIsNotTextLike(mediaType: MediaType) {
        assertThat(mediaType.isTextLike()).describedAs(mediaType.toString()).isFalse()
    }
}